<?php

return [

    'per_page' => 6,

    'items' => [
        [
            'slug' => 'emergency-relief-campaign',
            'image' => 'images/news-1.jpg',
            'date_key' => 'site.news.item1_date',
            'title_key' => 'site.news.item1_title',
            'excerpt_key' => 'site.news.item1_excerpt',
            'body_key' => 'site.news.item1_body',
            'featured' => true,
        ],
        [
            'slug' => 'health-center-opening',
            'image' => 'images/news-2.jpg',
            'date_key' => 'site.news.item2_date',
            'title_key' => 'site.news.item2_title',
            'excerpt_key' => 'site.news.item2_excerpt',
            'body_key' => 'site.news.item2_body',
            'featured' => true,
        ],
        [
            'slug' => 'education-program-launch',
            'image' => 'images/news-3.jpg',
            'date_key' => 'site.news.item3_date',
            'title_key' => 'site.news.item3_title',
            'excerpt_key' => 'site.news.item3_excerpt',
            'body_key' => 'site.news.item3_body',
            'featured' => true,
        ],
        [
            'slug' => 'international-partnership',
            'image' => 'images/news-4.jpg',
            'date_key' => 'site.news.item4_date',
            'title_key' => 'site.news.item4_title',
            'excerpt_key' => 'site.news.item4_excerpt',
            'body_key' => 'site.news.item4_body',
            'featured' => true,
        ],
        [
            'slug' => 'winter-aid-distribution',
            'image' => 'images/news-1.jpg',
            'date_key' => 'site.news.item5_date',
            'title_key' => 'site.news.item5_title',
            'excerpt_key' => 'site.news.item5_excerpt',
            'body_key' => 'site.news.item5_body',
            'featured' => false,
        ],
        [
            'slug' => 'volunteer-training-workshop',
            'image' => 'images/news-2.jpg',
            'date_key' => 'site.news.item6_date',
            'title_key' => 'site.news.item6_title',
            'excerpt_key' => 'site.news.item6_excerpt',
            'body_key' => 'site.news.item6_body',
            'featured' => false,
        ],
        [
            'slug' => 'clean-water-project',
            'image' => 'images/news-3.jpg',
            'date_key' => 'site.news.item7_date',
            'title_key' => 'site.news.item7_title',
            'excerpt_key' => 'site.news.item7_excerpt',
            'body_key' => 'site.news.item7_body',
            'featured' => false,
        ],
        [
            'slug' => 'orphan-sponsorship-drive',
            'image' => 'images/news-4.jpg',
            'date_key' => 'site.news.item8_date',
            'title_key' => 'site.news.item8_title',
            'excerpt_key' => 'site.news.item8_excerpt',
            'body_key' => 'site.news.item8_body',
            'featured' => false,
        ],
        [
            'slug' => 'community-health-awareness',
            'image' => 'images/news-1.jpg',
            'date_key' => 'site.news.item9_date',
            'title_key' => 'site.news.item9_title',
            'excerpt_key' => 'site.news.item9_excerpt',
            'body_key' => 'site.news.item9_body',
            'featured' => false,
        ],
        [
            'slug' => 'food-security-initiative',
            'image' => 'images/news-2.jpg',
            'date_key' => 'site.news.item10_date',
            'title_key' => 'site.news.item10_title',
            'excerpt_key' => 'site.news.item10_excerpt',
            'body_key' => 'site.news.item10_body',
            'featured' => false,
        ],
        [
            'slug' => 'annual-report-release',
            'image' => 'images/news-3.jpg',
            'date_key' => 'site.news.item11_date',
            'title_key' => 'site.news.item11_title',
            'excerpt_key' => 'site.news.item11_excerpt',
            'body_key' => 'site.news.item11_body',
            'featured' => false,
        ],
        [
            'slug' => 'youth-empowerment-program',
            'image' => 'images/news-4.jpg',
            'date_key' => 'site.news.item12_date',
            'title_key' => 'site.news.item12_title',
            'excerpt_key' => 'site.news.item12_excerpt',
            'body_key' => 'site.news.item12_body',
            'featured' => false,
        ],
    ],

];
